### ISSUE TITLE
A 404 error occurred Page not found.

### ISSUE THREAD

**Issue by GaneshKandu** [libracms/libra-cms#14]
Hi,

Getting 404 error ( Page not found. ) at ```admin/libra-app/translation``` in libra 0.8.1
Configuration > Translation option
and images in article option are also 404 error

installed in sub-directory of web accessible folder 

is project live or death ?

**Comment by vnagara** [comment]
Hi,
"Translation" page is not implemented yet.
Can you give more details about " images in article option are also 404 error" ?
Thanks,

**Comment by GaneshKandu** [comment]
Libra is Installed in sub Directory
Image folder is empty from the images to be load

http://mydomain.com/sub-dir/libra/public/admin/article/article/edit/47

![img_20180514](https://user-images.githubusercontent.com/12833130/39986121-3bad25b0-5750-11e8-808c-4dd23b26e93c.png)

http://mydomain.com/sub-dir/libra/public/admin/article/article/edit/46

![img_20180514 1](https://user-images.githubusercontent.com/12833130/39986164-64f12ffc-5750-11e8-932f-0af526102b76.png)

**Comment by vnagara** [comment]
Hi, links doesn't work. 
Any way I have an idea what happens. When you use CMS from sub-directory you need to configure _ckfinder_ module that is located in  ___.../libra-cms/vendor/libra/ckfinder-assets/public/config.php___ for editing images.
Configure proper path to ___init_autoloader.php___ in  ___function CheckAuthentication()___ or just put there
~~~
  return true;
~~~

**Comment by GaneshKandu** [comment]
Sorry ! but still not working

**Comment by vnagara** [comment]
Did you put 
```
return true;
```
?

**Comment by GaneshKandu** [comment]
yes

**Comment by vnagara** [comment]
@GaneshKandu Aha, checked file again. there you have parameter for URL. U need to change it to appropriate.
Look up for this in the same file:
```
$baseUrl = '/stories/';
```

**Comment by GaneshKandu** [comment]
Sorry ! but i think this is because its hard coded in sql file in content column of article table
